# Generated by Django 5.1.4 on 2024-12-23 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SERVER_IP', models.CharField(max_length=100)),
                ('DURATION_1LTR', models.IntegerField(max_length=20)),
                ('DURATION_2LTR', models.IntegerField(max_length=20)),
                ('DURATION_3LTR', models.IntegerField(max_length=20)),
                ('DURATION_5LTR', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('mac', models.CharField(max_length=100, unique=True)),
                ('install_date', models.DateTimeField(auto_now_add=True)),
                ('last_seen_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reader.configuration')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.site')),
            ],
        ),
    ]
