# Generated by Django 5.1.4 on 2024-12-23 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Consumer', '0002_alter_membership_status'),
        ('Reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Gender', models.CharField(max_length=10)),
                ('DAILY_QUOTA', models.CharField(max_length=50)),
                ('ACTIVE_DATE', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Txn_DateTime', models.DateTimeField(auto_now_add=True)),
                ('CONSUMED_QTY', models.CharField(max_length=50)),
                ('BALANCE_QTY', models.CharField(max_length=50)),
                ('MEMBERSHIP_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Consumer.membership')),
                ('READER_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reader.reader')),
            ],
        ),
    ]
